arena:
  max-players: 10
  list-remove-block: SAND,GRAVEL
  complete: false
  spawn:
  loose-zone: 20
  reward:
    money:
      first-place:
        min: 10
        max: 100
      second-place:
        min: 10
        max: 50
      third-place:
        min: 10
        max: 25
      loser:
        min: 10
        max: 10
    experience:
      first-place:
        min: 10
        max: 100
      second-place:
        min: 10
        max: 50
      third-place:
        min: 10
        max: 25
      loser:
        min: 10
        max: 10

